# Generated by Django 4.2.2 on 2023-07-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
