# Generated by Django 4.2.2 on 2023-07-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_remove_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='query',
        ),
    ]
